Repository code-well0/trip-planner, pull requests merged in 2025-08, with the labels that each got.

#32 Feature/chatbot UI improvements
  .env.development
  .env.production
  DEPLOYMENT_GUIDE.md
  GEMINI_SETUP.md
  README.md
  package-lock.json
  package.json
  src/.env
  src/server.js
Labels: bug, enhancement, gssoc 25, level 3

#81 added react-toast
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/ExpenseTracker.jsx
  src/pages/HomeSplit.jsx
  src/pages/Signup.jsx
  src/pages/login.jsx
Labels: enhancement, gssoc 25, level 2

#82 Enhance UI/UX of Trip Recommender Page with Icons and Custom Fonts
  package-lock.json
  src/Components/Navbar.jsx
  src/index.css
  src/pages/TripRecommender.jsx
Labels: enhancement, good first issue, gssoc 25, level 1

#95 [Bug]:SignUp route fixed
  package-lock.json
  package.json
  src/App.js
  src/Components/Hero.jsx
  src/pages/HomeSplit.jsx
  src/pages/Signup.jsx
  src/pages/login.jsx
Labels: bug, gssoc 25, level 1

#101 Updated README.md
  README.md
Labels: documentation, good first issue, gssoc 25, level 1

#116 feat: update frontend to use Render backend URL
  .vercelignore
  GEMINI_SETUP.md
  src/pages/Chatbot.jsx
Labels: enhancement, gssoc 25, level 2

#135 Added Activity Planner page and navbar link
  src/App.js
  src/Components/Navbar.jsx
  src/pages/ActivityPlanner.css
  src/pages/ActivityPlanner.jsx
Labels: enhancement, gssoc 25, level 2

#134 create T&C
  src/App.js
  src/pages/terms.jsx
Labels: documentation, gssoc 25, level 1

#146 added expandable/collapsible destination cards with details
  src/App.js
  src/Components/Card.jsx
  src/data.js
  src/pages/TripDetails.jsx
Labels: enhancement, gssoc 25, level 2

#184 Created a Dedicated Homepage for Better Navigation
  package-lock.json
  src/App.js
  src/Components/ui/shape-landing-hero.jsx
  src/pages/Dashboard.jsx
  src/pages/Home.jsx
Labels: enhancement, gssoc 25, level 1
