Repository code-well0/trip-planner, pull requests merged in 2025-09, with the labels that each got.

#200 Added gsap animations on landing page
  package-lock.json
  package.json
  src/Components/FadeContent.jsx
  src/Components/SplitText.jsx
  src/pages/Home.jsx
Labels: enhancement, gssoc 25, level 2

#219 added blogs section in navbar
  src/App.js
  src/Components/Navbar.jsx
  src/pages/Blogs.jsx
Labels: enhancement, gssoc 25, level 2

#211 Feature/blog page
  .gitignore
  backend/blogs.json
  backend/package-lock.json
  backend/package.json
  backend/server.js
  src/App.js
  src/Components/Navbar.jsx
  src/pages/AddBlog.jsx
  src/pages/Blog.jsx
  src/pages/BlogDetail.jsx
Labels: enhancement, gssoc 25, level 2

#227 Removed the previous existing button
  src/App.js
  src/Components/BackToTop.jsx
  src/Components/Tours.jsx
Labels: good first issue, gssoc 25, level 1

#225 Enhanced Login Page UI
  src/pages/login.jsx
Labels: enhancement, gssoc 25, level 2

#236 Redesigned-contact-us-page
  src/pages/ContactUs.jsx
Labels: enhancement, gssoc 25, level 2

#226 NabBar items added and new cards in feature icon with heading
  src/Components/Hero.jsx
  src/Components/Navbar.jsx
  src/pages/Home.jsx
Labels: enhancement, gssoc 25, level 2

#241 Added Snake trail cursor effect
  src/App.js
  src/Components/SnakeCursor.jsx
Labels: enhancement, gssoc 25, level 2

#247 fix:markdown rendering in chatbot response
  package-lock.json
  package.json
  src/pages/Chatbot.jsx
Labels: bug, enhancement, gssoc 25, level 2

#254 Scroll to top on route change
  src/Components/BackToTop.jsx
Labels: enhancement, gssoc 25, level 2

#265 Ui enhancement for ai chatbot
  src/pages/Chatbot.jsx
Labels: enhancement, gssoc 25, level 1

#269 Real-time collaborative trip planning
  firestore.rules
  src/Components/Card.jsx
  src/Components/Tours.jsx
  src/lib/planModel.js
  src/lib/planModel.test.js
  src/pages/PlanTrip.jsx
Labels: enhancement, gssoc 25, level 3

#281 feat: Add a password strength checker
  backend/package-lock.json
  package-lock.json
  package.json
  src/pages/Signup.jsx
Labels: enhancement, gssoc 25, level 1
